services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: areeb_backend
    restart: unless-stopped
    environment:
      JWT_SECRET: ${JWT_SECRET:-change-me}
      REDIS_URL: redis://redis:6379
      PG_HOST: postgres
      PG_DB_NAME: areeb_db
      PG_USER: test
      PG_PASSWORD: test
      PG_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    networks:
      - areeb_network

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: areeb_migrate
    restart: "no"
    environment:
      DATABASE_URL: postgresql://test:test@postgres:5432/areeb_db
    depends_on:
      postgres:
        condition: service_healthy
    command: ["bun", "drizzle-kit", "push"]
    networks:
      - areeb_network

  seed:
    image: postgres:15-alpine
    container_name: areeb_seed
    restart: "no"
    environment:
      PGPASSWORD: test
    depends_on:
      postgres:
        condition: service_healthy
    command:
      ["sh", "-c", "psql -h postgres -U test -d areeb_db -f /seed/seed.sql"]
    volumes:
      - ./database/schema/seed.sql:/seed/seed.sql:ro
    networks:
      - areeb_network

  postgres:
    image: postgres:15-alpine
    container_name: areeb_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: areeb_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Add this line to mount the init scripts
      - ./database/schema:/docker-entrypoint-initdb.d
    ports:
      # Try using this IP to connect in pgadmin4 172.26.0.2
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d areeb_db"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - areeb_network

  # pgadmin:
  # image: dpage/pgadmin4
  # container_name: areeb_pgadmin
  # restart: unless-stopped
  # environment:
  #   PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #   PGADMIN_DEFAULT_PASSWORD: admin
  #   PGADMIN_CONFIG_SERVER_MODE: "False"
  # volumes:
  #   - pgadmin_data:/var/lib/pgadmin
  # ports:
  #   - "5050:80"
  # networks:
  #   - areeb_network
  # depends_on:
  #   - postgres

  redis:
    image: redis:latest
    container_name: areeb_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - areeb_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  areeb_network:
    name: areeb_network
    driver: bridge
